# Generated by Django 4.2.1 on 2024-11-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myquadric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('x1', models.TextField()),
                ('x2', models.TextField()),
            ],
        ),
    ]
