# Generated by Django 4.2.1 on 2024-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solves', '0002_myquadric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='myquadric',
            name='status_answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myquadric',
            name='x_answer_1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myquadric',
            name='x_answer_2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
