# Generated by Django 4.2.1 on 2024-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_teg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.IntegerField()),
                ('id_teg', models.IntegerField()),
            ],
        ),
    ]
