# Generated by Django 4.2.1 on 2024-11-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_image_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teg', models.CharField(max_length=1000)),
            ],
        ),
    ]
