# Generated by Django 4.2.1 on 2024-11-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_temp_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp_Table',
        ),
    ]
